### ISSUE TITLE
Add py.typed marker

### ISSUE THREAD

**Issue by Daverball** [ubernostrum/webcolors#19]
While the project seems to use type annotations internally, type checkers will ignore them because the `py.typed` marker file is missing. Note that adding the file will not be enough, since you will also need to explicitly add `py.typed` to the `package_data` so the `py.typed` marker is still there after installation.

**Comment by ubernostrum** [comment]
Hi,

The omission of the `py.typed` file is a deliberate choice for this package. My belief is that [PEP 561](https://peps.python.org/pep-0561/) (which introduced the requirement for that file) was badly designed at the time it was written, and has only aged poorly since then.

Summarizing so that I can link to this in future issues:

The `py.typed` file was introduced as, basically, a workaround for the fact that `mypy` attempted to support too many different mechanisms of supplying type hints, coupled with its insistence on continuing to support Python 2 for longer than was wise. The correct approach is for `mypy` to either simplify itself or deal with its own complexity in a more productive way, rather than using a PEP to try to force the rest of the world to work around `mypy`'s self-inflicted complexity.

And the requirement of including the `py.typed` file makes it impossible to, for example, ship a traditional single-file package -- as `webcolors` in fact was up until version 1.13, and some of my other open-source packages still are -- due to mandating that the installed package be a directory containing the `py.typed` file alongside the code.

So as a form of protest, I deliberately do not include a `py.typed` file in any of my own open-source packages. Users who want to run `mypy` against one of my packages are free to create, maintain, or contribute to a "stub" package instead. In the case of `webcolors`, someone has [already created a type stub package](https://pypi.org/project/webcolors-stubs/), and I would suggest you coordinate with that person if you're interested in updating it.
