### ISSUE TITLE
Feature request: detect and normalize colors

### ISSUE THREAD

**Issue by mikaelho** [ubernostrum/webcolors#7]
Would be excellent if the library included a function that accepted any of the color representations allowed in a CSS file, and normalized that to e.g. RGBA.

**Comment by ubernostrum** [comment]
I'm inclined to leave this out; `webcolors` doesn't handle all the legal formats to begin with (it doesn't support `hsl()` or `hsla()` tuples, and doesn't accept the CSS2 "system color" names). And parsing a color value out of an arbitrary string is actually extremely difficult; that's why the HTML5 legacy parsing algorithm (which *is* implemented, but doesn't do what you're asking for) is so complex.

**Comment by mikaelho** [comment]
Fully appreciate your commitment to full compliance. However, for reference and for others looking for something like this, I created a quick wrapper, available [here](https://github.com/mikaelho/youey/blob/master/youey/util/color.py). This allows you to work with colors, including the alpha channel, like this:

```
  c = Color()
  c0 = Color(c)
  c1 = Color(c.red, c.green, c.blue, c.alpha)
  c2 = Color('black')
  c3 = Color(0)
  c4 = Color('#000000')
  c5 = Color('rgb(0,0,0)')
  c6 = Color('rgba(0,0,0,1)')
  
  assert c0 == c1 == c2 == c3 == c4 == c5 == c6
  
  c7 = Color('navy')
  assert c7.css == 'rgba(0,0,128,1.0)'
  assert c7.name == 'navy'
  assert c7.hex == '#000080'
  
  assert Color(1).name == 'white'
  
  c.css = c7.css
  assert c == c7
  
  c9 = Color('transparent')
  assert c9 == [0,0,0,0]
  assert c9.name == 'black'
  assert c9.transparent == True
  c7.transparent = True
  assert c7 == Color('navy', alpha=0)
  
  assert c.contrast_color().name == 'white'
  assert c7.contrast_color().name == 'white'
  assert Color('yellow').contrast_color().name == 'black'
  assert Color('white').contrast_color().name == 'black'
```
