### ISSUE TITLE
Feature Request: generic parse function

### ISSUE THREAD

**Issue by luckydonald** [ubernostrum/webcolors#8]
I read through the documentation but couldn't find any function which simply allows throwing in any css color attribute and getting back RGB information.

```py
styles = {'color': 'hotpink', 'background-color': '#C0FFEE'}

webcolors.parse(styles['color'])
webcolors.parse(styles['background-color'])
```

**Comment by ubernostrum** [comment]
This isn't something that I plan to implement, since it would require supporting the non-RGB constructs, but if you just want to support RGB color constructs and don't care about HSL, alpha-channel, etc., you could easily write your own that just handles two cases:

1. Value begins with `rgb(`, in which case presence or absence of `%` in the value tells you whether it's an int or percent triplet, and you can use webcolors' conversion functions appropriately, or
2. Value is literally anything else, in which case throw it into the HTML5 legacy parse implementation, which will do the right thing for both named colors and 3- or 6-digit hex values.

**Comment by luckydonald** [comment]
I think web color names should be part of a library called `webcolors`.
